#################################################################
# Scons script for google test
# called by Scons script of Physika Test
# @author: Wei Chen,30/12/2016   
#################################################################

######################CONFIGURATIONS#############################
# IMPORT FROM PARENT SCONS SCRIPT
Import('release_env os_name os_architecture compiler')
#################################################################

#IMPORTS
import os
from os.path import basename
from glob import glob

release_env.Append(CPPPATH = './')

gtest_and_gmock_lib_src_file  = 'src/gmock-gtest-all.cc'
gtest_and_gmock_main_src_file = 'src/gmock_main.cc'

gtest_and_gmock_lib_file      = 'lib/gtest_and_gmock'
gtest_and_gmock_main_lib_file = 'lib/gtest_and_gmock_main'

release_env.StaticLibrary(target = gtest_and_gmock_lib_file, source = gtest_and_gmock_lib_src_file)
release_env.StaticLibrary(target = gtest_and_gmock_main_lib_file, source = gtest_and_gmock_main_src_file)